name: Build & Publish Development Image

on:
  push:
    tags: [ "v*.**" ]
    branches:
    - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Build Image
      id: buildah
      uses: redhat-actions/buildah-build@v2
      with: 
        image: ${{ github.repository}}
        tags: dev
        containerfiles: |
          ./Containerfile
        oci: true
    
    - name: Publish Image
      id: publish
      uses: redhat-actions/push-to-registry@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        image: ${{ github.repository }}
        tags: dev
    
    - name: Output Image Location
      run: echo "Image published to ${{ steps.publish.output.registry-paths }}"
